Sprint 7 solution in file manager
ChakNikolay87/java-kanban pull request #11
Opened 2024-09-11 09:41 UTC by ChakNikolay87

2024-09-12 08:19 UTC, NikolaiDem requested changes
Проект в текущем виде не комплилируется. Нужно проверить, все ли было закоммичено

2024-09-12 08:19 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager
> +public class FileBackedTaskManager extends InMemoryTaskManager {
Точно ли файл этого класса имеет расширение java?

2024-09-13 09:48 UTC, ChakNikolay87 commented
Добрый день! Исправил все замечания, все компилируется

2024-09-14 07:25 UTC, NikolaiDem requested changes

2024-09-14 07:25 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +    private String taskToString(Task task) {
Метод taskToString() можно сделать в самой Task и переопределить его в Epic и Subtask, тогда не будет нужен instanceOf

2024-09-14 07:25 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        if (task instanceof Subtask) {
Можно добавить метод type() в самой Task и переопределить его в Epic и Subtask, тогда не будет нужен instanceOf

2024-09-14 07:25 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +
Почему не переопределены методы удаления всех тасок, сабтасок и эпиков. А также метода запроса по id?

2024-09-14 07:25 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        TaskStatus status = TaskStatus.valueOf(fields[3]);
Почему не используется status?

2024-09-14 07:25 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +                return new Epic(id, name, description);
У эпика нужно восстановить его сабтаски

2024-09-16 09:45 UTC, ChakNikolay87 commented
Добрый день! Исправил замечания

2024-09-17 00:35 UTC, NikolaiDem requested changes

2024-09-17 00:35 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +                    manager.createSubtask(subtask);
Точно ли количество сабтасок в итоге будет верным?

2024-09-17 00:35 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +                        manager.createEpic((Epic) task);
При вызове методов создания у эпиков будут другие id чем до сохранения.
Аналогично для эпиков и сабтасок

2024-09-17 00:35 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        Task task = super.getTaskById(id);
Такое переопределение можно не делать. Ничем не отличается от родительского вызова

2024-09-17 05:57 UTC, ChakNikolay87 commented
Добрый день! Внес изменения в метод loadFromFile и удалил ненужные переопределения методов.

2024-09-17 22:54 UTC, NikolaiDem requested changes

2024-09-17 22:54 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +public class FileBackedTaskManagerTest {
Создать тест, в котором проверяется, что состояние менеджера до сохранения и после сохранения в файл совпадают. При этом использовать все виды задач.

2024-09-22 07:40 UTC, closed without merging